/** Central query key factory. Feature pages add their keys here so invalidation stays consistent. */
type P = Record<string, unknown> | undefined;

export const queryKeys = {
  me: ['me'] as const,
  demoAccounts: ['auth', 'demo-accounts'] as const,
  search: (q: string) => ['search', q] as const,
  notifications: {
    all: ['notifications'] as const,
    list: (filter: string) => ['notifications', filter] as const,
  },
  attachments: (entityType: string, entityId: string) => ['attachments', entityType, entityId] as const,
  home: ['home'] as const,
  challenges: {
    all: ['challenges'] as const,
    list: (p?: P) => ['challenges', 'list', p ?? {}] as const,
    detail: (slugOrId: string) => ['challenges', 'detail', slugOrId] as const,
    questions: (id: string) => ['challenges', id, 'questions'] as const,
    entries: (id: string) => ['challenges', id, 'entries'] as const,
    demoSlots: (id: string) => ['challenges', id, 'demo-slots'] as const,
  },
  entries: {
    all: ['entries'] as const,
    mine: ['entries', 'mine'] as const,
    detail: (id: string) => ['entries', 'detail', id] as const,
    submissions: (id: string) => ['entries', id, 'submissions'] as const,
    submission: (id: string, kind: string) => ['entries', id, 'submission', kind] as const,
    feedback: (id: string) => ['entries', id, 'feedback'] as const,
    milestones: (id: string) => ['entries', id, 'milestones'] as const,
  },
  teams: {
    detail: (id: string) => ['teams', id] as const,
    inviteLinks: (id: string) => ['teams', id, 'invite-links'] as const,
    joinRequests: (id: string) => ['teams', id, 'join-requests'] as const,
    join: (token: string) => ['join', token] as const,
  },
  ideas: {
    all: ['ideas'] as const,
    list: (p?: P) => ['ideas', 'list', p ?? {}] as const,
    detail: (code: string) => ['ideas', 'detail', code] as const,
    history: (id: string) => ['ideas', id, 'history'] as const,
  },
  review: {
    queue: ['review', 'queue'] as const,
    assignment: (id: string) => ['review', 'assignment', id] as const,
    round: (id: string) => ['review', 'round', id] as const,
    results: (id: string) => ['review', 'round', id, 'results'] as const,
    feedback: (id: string) => ['review', 'round', id, 'feedback'] as const,
  },
  shortlists: { detail: (id: string) => ['shortlists', id] as const },
  submissions: {
    list: (p?: P) => ['submissions', 'list', p ?? {}] as const,
    detail: (id: string) => ['submissions', 'detail', id] as const,
  },
  manage: {
    challenges: (p?: P) => ['manage', 'challenges', p ?? {}] as const,
    challenge: (id: string) => ['manage', 'challenge', id] as const,
    results: (id: string) => ['manage', 'challenge', id, 'results'] as const,
  },
  results: ['results'] as const,
  catalogue: (p?: P) => ['catalogue', p ?? {}] as const,
  impact: ['impact'] as const,
  dashboards: (type: string, p?: P) => ['dashboards', type, p ?? {}] as const,
  comments: (entityType: string, entityId: string) => ['comments', entityType, entityId] as const,
  milestones: (entityType: string, entityId: string) => ['milestones', entityType, entityId] as const,
  kpis: (entityType: string, entityId: string) => ['kpis', entityType, entityId] as const,
  recognition: ['me', 'recognition'] as const,
  masterdata: {
    domains: ['domains'] as const,
    categories: ['categories'] as const,
    lookups: (type: string) => ['lookups', type] as const,
    skills: ['skills'] as const,
    orgUnits: ['org-units'] as const,
    users: (q: string) => ['users', q] as const,
  },
  admin: {
    users: (p?: P) => ['admin', 'users', p ?? {}] as const,
    roles: ['admin', 'roles'] as const,
    forms: ['admin', 'forms'] as const,
    form: (id: string) => ['admin', 'forms', id] as const,
    scorecards: ['admin', 'scorecards'] as const,
    scorecard: (id: string) => ['admin', 'scorecards', id] as const,
    workflows: ['admin', 'workflows'] as const,
    templates: ['admin', 'notification-templates'] as const,
    rules: ['admin', 'notification-rules'] as const,
    deliveries: (p?: P) => ['admin', 'notification-deliveries', p ?? {}] as const,
    settings: ['admin', 'settings'] as const,
    flags: ['admin', 'feature-flags'] as const,
    audit: (p?: P) => ['admin', 'audit', p ?? {}] as const,
    health: ['admin', 'system-health'] as const,
  },
};
